### ISSUE TITLE
<button> component behaves weirdly.

### ISSUE THREAD

**Issue by DocSeattle** [lia-2-team-1/webbsite#18]
<Button> component behaves weirdly when wrapping to accommodate smaller screen widths.
Especially when its own content has lots of text.

**Comment by karinEkenberg** [comment]
It is also weird in normal screensizes.

**Comment by karinEkenberg** [comment]
![KNAPPKNAS](https://github.com/user-attachments/assets/38c0a6cd-7275-46b3-a581-b1fbf78995f9)

**Comment by DocSeattle** [comment]
> It is also weird in normal screensizes.

This behaviour is expected; I'll see about iterating on the component to make it adaptible to longer text.

**Comment by DocSeattle** [comment]
This was resolved in the revised button component.
